name: dashboardx
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_svg: ^0.14.4
  rxdart: ^0.22.6
  built_value: ^7.0.0
  intl: ^0.16.0
  camera: ^0.5.6+3
  preferences: ^4.0.0
  noise_meter: ^1.0.1
  permission_handler: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  flutter_launcher_icons: ^0.7.4
  provider: ^3.1.0

flutter:
  uses-material-design: true

