name: dashboardx
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_svg: ^0.14.4
  rxdart: ^0.22.6
  built_value: ^7.0.0
  intl: ^0.16.0
  camera: ^0.5.6+3
  preferences: ^4.0.0
  path_provider: ^1.4.2
  provider: ^3.1.0
  firebase_ml_vision: ^0.9.3+3
  firebase_core: ^0.4.1+5
  noise_meter: ^1.0.1
  permission_handler: ^4.0.0
  carousel_slider: ^1.3.1
  dots_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Averta CY
      fonts:
        - asset: fonts/Averta-Cyrillic-Regular.otf
        - asset: fonts/Averta-Cyrillic-SemiBold.otf
          weight: 600
        - asset: fonts/Averta-Cyrillic-Bold.otf
          weight: 700